/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_fuwei_asr_SpeechTranscript_modular_service_JniShmService */

#ifndef _Included_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
#define _Included_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_shmInit
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1shmInit
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_readSpeechRecordShm
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1readSpeechRecordShm
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_readSpeechRecordByteArrShm
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1readSpeechRecordByteArrShm
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_writeTextRecordShm
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1writeTextRecordShm
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_shmTerm
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1shmTerm
  (JNIEnv *, jobject);

////////////////////////////////////////////////////////////////////////////////

void callback_printLogInfo(JNIEnv *pEnv, jobject object, const char* info);

void callback_printLogError(JNIEnv *pEnv, jobject object, const char* error);

////////////////////////////////////////////////////////////////////////////////

/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_shmSpeechPacketReceive
 * Signature: (Ljava/lang/Integer;ZILjava/lang/Integer;Ljava/lang/Boolean;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1shmSpeechPacketReceive
  (JNIEnv *, jobject, jint, jboolean, jint, jobject, jobject);

/*
 * Class:     com_fuwei_asr_SpeechTranscript_modular_service_JniShmService
 * Method:    JNI_shmTextPacketSend
 * Signature: (Ljava/lang/Integer;Lcom/fuwei/asr/SpeechTranscript/modular/controller/AsrResponse;)V
 */
JNIEXPORT void JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1shmTextPacketSend
  (JNIEnv *, jobject, jint, jobject);

JNIEXPORT void JNICALL Java_com_fuwei_asr_SpeechTranscript_modular_service_JniShmService_JNI_1shmTextPacketSend
  (JNIEnv *, jobject, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
